### PR TITLE
Standarise .env file naming convention

### PR DESCRIPTION
**Pull request by php4umagento**
## This PR is a:

[ ] New feature
[X ] Enhancement/Optimization
[ ] Refactor
[ ] Bugfix
[ ] Test for existing code
[ X] Documentation

## Summary

When this pull request is merged, it will rename example.env into .env.dist
 This is more widely used approach

## Additional information

Also changed documentation and circleci test

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento-research/pwa-studio?pullRequest=384) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento-research/pwa-studio?pullRequest=384) before we can accept your contribution.<br/>

**Comment by ericerway** [comment]
Thanks for the PR @php4umagento! We will review this week with Sprint 27. /cc @zetlen

**Comment by mage2pratik** [comment]
@php4umagento @ericerway 
I'm just checking Venia Storefront and I found example.env on following path:
https://github.com/magento-research/pwa-studio/blob/release/2.0/packages/venia-concept/example.env

**Comment by php4umagento** [comment]
@mage2pratik - I am proposing to rename {{example.env}} into {{.env.dist}}

**Comment by zetlen** [comment]
Thank you for noticing this. At one point it was called `.env.dist` and I renamed it to `example.env` to make it clearer to developers who are new to using environment variables this much. I agree that `.env.dist` is more common, but I think it's less clear. I'm holding this PR until we add automation to autogenerate or auto-update `.env`, but then I'll merge it.

**Comment by zetlen** [comment]
Automation added. Thanks for noticing this!

**Pull request closed without merging**
