### PR TITLE
bug: throwing  error while pulling cms block(s).

### LINKED ISSUE #620: CMS blocks don't render
As a developer I want to be able to add CMS block content using the `<CmsBlocks />` as suggested in merged PR https://github.com/magento-research/pwa-studio/pull/277 . However CMS blocks don't render.

## This issue is for the following packages:

- [x] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

## This issue is a:

- [x] Bug
- [ ] Feature suggestion
- [ ] Documentation issue
- [ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             | 2.3.0 |
| Operating System + version  | Ubuntu Bionic |
| node.js version (`node -v`) | 8.11.3 |
| npm version (`npm -v`)      | 6.4.1 |

## Description

1) Add CMS block with identifier 'home-venia'  to a 2.3 Magento install
2) Add following to  `packages/venia-concept/src/RootComponents/CMS/CMS.js` 

```jsx
import React, { Component } from 'react';
import CategoryList from 'src/components/CategoryList';
import CmsBlock from 'src/components/CmsBlock';

export default class CMS extends Component {
    render() {
    return ( 
        <div>
            <CategoryList title="Shop by category" id={2} />
            <CmsBlock identifiers={'home-venia'} />
        </div>
    )}
}
```

3) Page errors out with: `Cannot destructure property 'items' of undefined or NULL ` . 

Screenprint page won't render when existing CMS block is fetched:

magento-pwa-studio-issue-cmsblocks-error

## Expected result:

Page should render CMS Block that has been added to Magento Back-end.

## Possible solutions:

Destructuring items from data.cmsBlocks instead of data.blocks in https://github.com/magento-research/pwa-studio/blob/release/2.0/packages/venia-concept/src/components/CmsBlock/cmsBlock.js#L32 . So this will read   ` const { items } = data.cmsBlocks; `

Screenprint: fixed issue CMS block is shown:

magento-pwa-studio-issue-cmsblocks-fixed

Note: 
- kind of similar solution has been added in PR https://github.com/magento-research/pwa-studio/pull/507 . However this is still pending Venia sample CMS content, see issue https://github.com/magento-research/pwa-studio/issues/365 . So this minor fix will at least add the possibility to add any CMS block content (for those who are starting to build upon custom Magento 2.3 instance) independent from Venia CMS sample content that is due.
- I realize this probably isn't an urgent issue and depends on CMS sample content for Venia as well, see above. However as functionality seems not to work as intended, I have raised this as a separate issue.

### PR DESCRIPTION
**Pull request by kanhaiya5590**
venia-concept/src/queries/getCmsBlocks.graphql  we have *cmsBlocks* not *blocks*

## Related Issue

Closes #620.

## Proposed Labels for Change Type/Package
 What types of changes does your code introduce? Let us know if this is a
BUG

 What packages are modified by this code? Let us know if this applies to 
 venia-concept 

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] I have linked an issue to this PR.
- [x] I have indicated the change type and relevant package(s).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] All CI checks are green (linting, build/deploy, etc).
- [x] At least one core contributor has approved this PR.

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento-research/pwa-studio?pullRequest=915) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento-research/pwa-studio?pullRequest=915) before we can accept your contribution.<br/>

**Comment by sirugh** [comment]
@kanhaiya5590 thanks for your contribution! Before we can merge this you'll need to sign the CLA, linked above. Also would you mind filling out the sections in the PR template? They are there to make the whole contribution/review process smoother. Thanks!

**Comment by kanhaiya5590** [comment]
@sirugh signed the CLA, 

Thanks

**Comment by rossmc** [comment]
@sirugh can this PR be approved?  The fix looks good to me

**Pull request merged**
