### PR TITLE
enhancement(load): Branded first renders

### LINKED ISSUE #1272: [bug]: Unloaded states have inconsistent style
We have:
- hand-coded HTML behind a `<noscript>` tag for no-JS browsers
- simple placeholder text while the initial bundles load
- a nice loading indicator
- a static "not found" page

**To Reproduce**
1. Open Chrome dev tools.
2. Enter Mobile Emulation Mode.
3. Drop down the "No throttling" menu and select "Fast 3G" (or equivalent).
4. Visit venia.magento.com

**Expected behavior**
A smooth loading experience.

**Screenshots**

First Homepage Paint
First Homepage Paint

App data loading for all screens
App data loading for all screens

Page not found, loading
Page not found, loading

Page not found, loaded
Page not found, loaded

JS Disabled
JS Disabled

These states are wildly inconsistent with one another! They need to be brought in line.

**Additional context**
Related to #46, where we talk about our offline solutions in general.
We may have some future way of compiling certain React components down into static templates, or extracting critical CSS. However we fix this, it'll be a first pass.

**Possible solutions**
Add some minimal inlined CSS to visually match the in-app loading indicator. Replace the "Loading" text in the template with a styled version.

Rebuild the `js-unavailable` partial to reuse this style, to keep page size low.

**Please complete the following device information:**
 - iPhone SE in screenshots
 - PWA Studio Version: 2.1.0

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

### PR DESCRIPTION
**Pull request by zetlen**
## Description

Refactor Mustache templates to share a small critical CSS block and use it to render a branded first paint.

Add a general concept of `resource.name` to UPWARD, enabling the loading indicator to be a shared partial which uses `resource.name` and can therefore be customized per page.

Refactor noscript and 404 pages to use the same basic system.

## Related Issue
Closes #1272 

## Verification Steps

1. Go to a nonexistent page with an HTML extension, like `/nothing.html`. **Verify Not Found page.**  
  magento-venia-concept-fquwg local pwadev_8436_nothing html(iPhone 5_SE)
magento-venia-concept-fquwg local pwadev_8436_nothing html(iPhone 5_SE) (1)

2. Edit `packages/venia-concept/templates/seed-bundles.mst` and type garbage in the `src` attribute so the app doesn't load.

```mustache
{{#assets.bundles.load}}
    <script defer src="bsdasbd{{.}}"></script>
{{/assets.bundles.load}}
```

3. Go to homepage. **Verify branded first render.**

magento-venia-concept-fquwg local pwadev_8436_(iPhone 5_SE)
magento-venia-concept-fquwg local pwadev_8436_(iPhone 5_SE) (1)

4. Go to category page: `/venia-tops.html`. **Verify branded first render.**
magento-venia-concept-fquwg local pwadev_8436_venia-tops html(iPhone 5_SE)

5. Go to product page: `/carmina-earrings.html`. **Verify branded first render.**  
  magento-venia-concept-fquwg local pwadev_8436_carmina-earrings html(iPhone 5_SE)

6. Open Chrome Developer tools, open the Command Palette (Cmd-Shift-P on OSX) and type "Disable JavaScript". Press Enter.

7. Refresh page. **Verify branded no-script experience.**
magento-venia-concept-fquwg local pwadev_8436_carmina-earrings html(iPhone 5_SE) (1)
magento-venia-concept-fquwg local pwadev_8436_carmina-earrings html(iPhone 5_SE) (2)

## How Have YOU Tested this?
Portrait and landscape orientation on many, many browsers and devices.

## Proposed Labels for Change Type/Package

- [ ] major (e.g x.0.0 - a breaking change)
- [x] minor (e.g 0.x.0 - a backwards compatible addition)
- [ ] patch (e.g 0.0.x - a bug fix)

## Checklist:

- [x] I have updated the documentation accordingly, if necessary.
- [x] I have added tests to cover my changes, if necessary.

### CODE REVIEW

**Comment by sirugh** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  node` failed.
  </td>
    </tr>
  </tbody>
</table>



### Log


```sh
Error:  Error: Could not find a `dangerfile.js` or `dangerfile.ts` in the current working directory.
    at Object.dangerfilePath (/codebuild/output/src793756237/src/github.com/magento-research/pwa-studio/node_modules/danger/distribution/commands/utils/fileUtils.js:26:11)
    at Object.<anonymous> (/codebuild/output/src793756237/src/github.com/magento-research/pwa-studio/node_modules/danger/distribution/commands/danger-runner.js:92:42)
    at step (/codebuild/output/src793756237/src/github.com/magento-research/pwa-studio/node_modules/danger/distribution/commands/danger-runner.js:33:23)
    at Object.next (/codebuild/output/src793756237/src/github.com/magento-research/pwa-studio/node_modules/danger/distribution/commands/danger-runner.js:14:53)
    at fulfilled (/codebuild/output/src793756237/src/github.com/magento-research/pwa-studio/node_modules/danger/distribution/commands/danger-runner.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)

```

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against cdb0809537d1b4577922dd9da8e1579bb8189f0c
</p>

**Comment by soumya-ashok** [comment]
@zetlen This is the mockup I have for a general "Page not found" use-case - https://magento.invisionapp.com/share/KEPIS7TUG4X

Please let me know if any modifications need to be made for this specific instance.

**Comment by soumya-ashok** [comment]
@zetlen On the loading indicator and text, there is a size and treatment for both that we are following on other pages, so would be good to keep that consistent here as well.

**Comment by zetlen** [comment]
@soumya-ashok I copied the loading indicator style into the app shell, so it should be consistent. Here's a screenshot of the first loading indicator being replaced with the second.

branded-load-transition

**Comment by zetlen** [comment]
@soumya-ashok One other thing: is it okay if the header style for the page-not-found is different? Do you want it to be smaller, bold, and black, or is this okay?
magento-venia-concept-fquwg local pwadev_8436_askjdhgasd html(iPhone 5_SE)

FYI, I'm not nitpicking the design itself; I'm just trying to keep the app shell small, so the fewer CSS rules to write, the better.

**Comment by supernova-at** [comment]
@jzetlen is this ready for review? We're scared by the DO NOT MERGE text.

**Comment by soumya-ashok** [comment]
@zetlen could we make the text color the same as all the rest? I believe it is #212121. We can tweak the size later.

**Comment by dpatil-magento** [comment]
@sirugh  Created bug #1289 for issue mentioned above.

**Comment by dpatil-magento** [comment]
@soumya-ashok  Should there be any header for search results page?  `/search.html?query=top`  , currently its just icon with Loading text.


image

**Comment by zetlen** [comment]
@soumya-ashok @dpatil-magento Thanks for noticing that! I added some stuff to venia-upward.yml to add a proper title to the search page. I made the title quickly, without knowing which mockup to use. Please let me know how exactly this should look.

image

**Comment by soumya-ashok** [comment]
@dpatil-magento The search results page would have the same header as other pages on the site. Is that not the case now?

**Comment by dpatil-magento** [comment]
This ticket looks good now. As discussed in stnd-up, created follow-up ticket #1301 for new UX work required and assigned to @soumya-ashok .
@sirugh If latest changes looks good then please approve and merge the ticket.

**Comment by sirugh** [comment]
It says there's a merge conflict. I'll look tomorrow when I get in.

**Comment by soumya-ashok** [comment]
@zetlen The original design for the loading indicator is at the center of the screen but that is not how it has been implemented. If it is not too much work to fix that, that would be preferable but you can also keep it where it is now, and follow the template in the image attached.
By page name I mean - "Home" "Product details" "Search results" etc. - will this work?

**Comment by zetlen** [comment]
@jimbo In order to use CSS modules as critical inline style in the app shell, we'll have to add an extract plugin to the Buildpack pipeline. That's a little bit more invasive of a change than just this. Either we do this as a stopgap, or we don't do it, but either way, we need to replace it with something that reuses app style properly, ASAP.

So I'll leave it to you to make the call. We can close this if you'd rather leave the Times New Roman unstyled loads and 404s until we have proper critical CSS.

**Comment by zetlen** [comment]
> By page name I mean - "Home" "Product details" "Search results" etc. - will this work?
> 
> Text color #212121
> 
> 

@soumya-ashok The page name can include the name of the actual entity: whether it's the product ("Carmina Earrings") or the category "Accessories" or a search result for the query "green". Do you want to _not_ include that dynamic data and just say "Product details", "Category" above the loading spinner?

**Comment by soumya-ashok** [comment]
Yes, my preference would be to keep it generic for this first iteration, since we are working on a more detailed strategy for the future.

**Comment by zetlen** [comment]
@soumya-ashok OK, update pushed! In both the first-paint and intra-page loading indicators, you should now have a fully vertically centered UI.

**Comment by sirugh** [comment]
@dpatil-magento merge conflict and any missing stuff has been added!

**Pull request merged**
