### PR TITLE
documentation: Corrected media path variables

### PR DESCRIPTION
**Pull request by yogeshsuhagiya**
## Description
- Correct the name of media path environment variables for the product & category. 

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have linked an issue to this PR.
- [ ] I have indicated the change type and relevant package(s).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] All CI checks are green (linting, build/deploy, etc).
- [ ] At least one core contributor has approved this PR.

### CODE REVIEW

**Comment by yogeshsuhagiya** [comment]
@sirugh Is there anything that needs from my side?

**Comment by yogeshsuhagiya** [comment]
Hi @sirugh, It has been 10+ days but still no progress with this PR. Can you please check?

**Comment by sirugh** [comment]
@yogeshsuhagiya we've been actively working on getting our `2.1.0` release out the door. We've also got a big backlog of other pull requests to prioritize, review, qa, etc. It's a lot of work for a small team to handle. While we love to see community contributions they may not be at the top of our "to-do" list. Your patience is greatly appreciated.

**Comment by yogeshsuhagiya** [comment]
Hi @sirugh, sorry but how many more days I've to wait? The `2.1.0` version already released but still no progress.

**Comment by sirugh** [comment]
This was already fixed in #1039 but the doc/comment portion of `.env.dist` was not updated. 👍

**Pull request merged**
