### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by vdiachenko**
Spelling mistake

## This PR is a:

[ ] New feature
[ ] Enhancement/Optimization
[ ] Refactor
[ ] Bugfix
[ ] Test for existing code
[ ] Documentation

## Summary

When this pull request is merged, it will...

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento-research/pwa-studio?pullRequest=207) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento-research/pwa-studio?pullRequest=207) before we can accept your contribution.<br/>

**Comment by jcalcaben** [comment]
Thanks for the contribution @vdiachenko ! Please sign out CLA so I can merge your change.

**Comment by vdiachenko** [comment]
@jcalcaben ready.

**Comment by zetlen** [comment]
@vdiachenko Thanks for the help! The reason the test suite failed is that we configured CI not to export our secret tokens to forked pull requests. We've started exporting them, because they have very few permissions and it's pretty safe, but all the same...it will be a lot easier to open PRs if you can push branches directly to this repository, so I've made you a member and now you can! 🎉

**Comment by vdiachenko** [comment]
@zetlen thanks! :blush:

**Pull request merged**
