### PR TITLE
Feature/zoom gallery product

### LINKED ISSUE #1276: [feature]: Implement Image gallery with zoom
**Description**
*Implement Zoom gallery in product detail page*
Packages used 
React magnify: https://www.npmjs.com/package/react-image-magnify
React Slick: https://www.npmjs.com/package/react-slick

Screenshot 2019-05-28 at 6 47 56 PM

Screenshot 2019-05-28 at 6 48 38 PM

**Please let us know what packages this feature is in regards to:**
- [x] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

### PR DESCRIPTION
**Pull request by binucorra**
## Related Issue

Closes #1276 

## Verification Steps

1. Go product detail page.
https://venia-jn8dvoshz.now.sh/valeria-two-layer-tank.html
2. Mouse over on the main image.
3. Make sure zoom image is showing inline.

## Proposed Labels for Change Type/Package

- [ ] major (e.g x.0.0 - a breaking change)
- [ ] minor (e.g 0.x.0 - a backwards compatible addition)
- [ ] patch (e.g 0.0.x - a bug fix)

## Checklist:

- [ ] I have updated the documentation accordingly, if necessary.
- [ ] I have added tests to cover my changes, if necessary.

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento-research/pwa-studio?pullRequest=1277) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento-research/pwa-studio?pullRequest=1277) before we can accept your contribution.<br/>

**Comment by sirugh** [comment]
Closing this as we are in the middle of refactoring the PDP images in #1268. I've also requested that UX take a look at your original issue so we can discuss whether or not this is a feature we want to implement within our example storefront. Thanks for your contribution, though! In the future, if you open an issue beforehand we can discuss approaches before you spend too much time writing code :)

**Comment by sanganinamrata** [comment]
@sirugh Hello, Any update on zoom gallery feature on PWA studio?

**Comment by dawidow** [comment]
I also with a question, will this topic be continued?

**Pull request closed without merging**
