### PR TITLE
[Documentation] Migrate UPWARD docs to devdocs

### LINKED ISSUE #181: [Documentation] Middle-tier architecture
## This issue is for the following packages:

[ ] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-module`
[X] `pwa-devdocs`

## This issue is a:

[ ] Bug
[ ] Feature suggestion
[ ] Documentation issue
[X] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

As a developer I want to understand the impact of the updated middle-tier architecture changes for PWA Studio and how they affect developing and building storefronts including the Venia reference.

## Expected result:

Updated documentation
Internal and external review
Additional reference diagrams (as appropriate)

## Possible solutions:

Topics that cover the following:

* Basic concepts - provides information about concepts used by or introduced in UPWARD
* Context reference - Explains the global namespace, a.k.a. the context, and its usage in an UPWARD spec. Explains how to set/get values in the context. [Link to dev notes](https://github.com/magento-research/pwa-studio/tree/release/2.0/packages/upward-spec#context-reference).
* Resolver reference - Describes what a resolver does. Provides detailed descriptions/examples of the different types of resolvers. [Link to dev notes](https://github.com/magento-research/pwa-studio/tree/release/2.0/packages/upward-spec#resolver-reference)

### PR DESCRIPTION
**Pull request by jcalcaben**
## Description

Migrate docs content from the [UPWARD spec README][] file into separate pages under a docs directory in that same package.

[UPWARD spec README]: https://github.com/magento-research/pwa-studio/blob/release/2.0/packages/upward-spec/README.md

## Related Issue

Closes #181 

## Motivation and Context

Cleaning up long README file.

## How Has This Been Tested?

N/A

## Screenshots (if appropriate):

N/A

## Proposed Labels for Change Type/Package

`documentation`

`pkg:pwa-devdocs`

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] I have linked an issue to this PR.
- [x] I have indicated the change type and relevant package(s).
- [x] I have updated the documentation accordingly.
- [ ] ~I have added tests to cover my changes.~
- [ ] All new and existing tests passed.
- [ ] All CI checks are green (linting, build/deploy, etc).
- [ ] At least one core contributor has approved this PR.

### CODE REVIEW

**Comment by zetlen** [comment]
@jcalcaben I'm actually not sure about this. I don't want to disrupt the devdocs workflow if I can help it, but I'd rather the spec and test suite be a single self-documenting package.

Taking the [GraphQL spec as a model](https://github.com/facebook/graphql), we could even move the upward-spec into its own repo eventually (though I don't want to do that yet). In general I want to encourage community contribution and pull requests to this material, beyond the Magento and PWA Studio horizons. If you think it's too early for that ambition, I understand, but my instinct is that a specification like this should live by itself, in a simple and accessible format, with no required build process.

**Comment by jcalcaben** [comment]
@zetlen I've moved the documentation into a docs directory and revised the core README file to point to separate doc files instead of keeping all the content in one long doc.

**Comment by zetlen** [comment]
@jcalcaben Confirming that it's ok to close this PR pending finalization of UPWARD doc plans.

**Comment by jcalcaben** [comment]
Sure thing

**Comment by supernova-at** [comment]
Both issue and PR are closed.

**Pull request closed without merging**
