### PR TITLE
fixed small_image doesn't have sub section error

### PR DESCRIPTION
**Pull request by dani97**
This bug caused data_error in category section

## This PR is a:
[ ] Bugfix

## Summary

When this pull request is merged, it will cause category page to load

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento-research/pwa-studio?pullRequest=355) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento-research/pwa-studio?pullRequest=355) before we can accept your contribution.<br/>

**Comment by ericerway** [comment]
Thanks for the PR @dani97! We will review right away. /cc @zetlen

**Comment by zetlen** [comment]
Thank you @dani97 ! This is a schema compatibility issue; as https://github.com/magento/magento2/commits/2.3-develop merges pull requests, its GraphQL schema updates, and sometimes those updates are breaking changes. Can you please backmerge `release/2.0` into your branch? This change may already have been merged from #318 /

**Comment by dani97** [comment]
@zetlen  thanks now I have understood.

**Pull request closed without merging**
