### PR TITLE
Authenticated Users

### LINKED ISSUE #655: [Bug]: Authorized user cannot add product to cart
## This issue is for the following packages:

- [X] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

## This issue is a:

- [X] Bug
- [ ] Feature suggestion
- [ ] Documentation issue
- [ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description
Steps to reproduce:
**Precondition**:
- clear all site data such as cookies, service worker cache, etc.
**Steps**:
- in the main page, choose any category, e.g. `shop-the-look`
- choose any product and click them
- open the left menu and click the `sign in` button
- type user credentials (username and password) and click the `sign in` button
- close left menu
- try to click `add to cart` on the currently opened item

- nothing happens, even request for adding on the cart not send

## Expected result:
Request sending and work correctly(add an item to cart)
Cart menu must open after sending a request

### PR DESCRIPTION
**Pull request by supernova-at**
## Description

This PR adds support for authenticated users. Specifically, it:
  * Updates `guestCartId` to `cartId` in `cart`
  * Updates appropriate REST calls to use the authenticated endpoint if the user is signed in
  * Updates the `<CheckoutReceipt>` component to not prompt the user to sign in if they are already signed in
  * Enables an authenticated user to complete the checkout flow

## Related Issue

Closes #655 .

## Motivation and Context

The codebase contained many `TODO`s that exited early when the user was signed in. There were many bugs surrounding the inability to perform various checkout actions once you signed in.

### Unit Tests

1. `yarn test`

### Guest Customers

Visit the Venia storefront as a guest user (sign out if needed), and ensure you can perform the following without error:

1. Add an item to the cart
1. Edit an item in the cart
1. Remove an item from the cart
1. Checkout successfully

### Authorized Customers

Visit the Venia storefront as a guest user (sign out if needed), and ensure you can perform the following without error:

1. Sign in
1. Add an item to the cart
1. Edit an item in the cart
1. Remove an item from the cart
1. Checkout successfully

### Switch Back

Visit the Venia storefront and check out as a signed-in user. Ensure you can perform the following without error:

1. Sign out
1. Add an item to the cart
1. Edit an item in the cart
1. Remove an item from the cart
1. Checkout successfully

📝 Note that this PR does **not** solve for customers switching between logged in and logged out during the checkout process or preserving items / carts between the two states. See [this comment](https://github.com/magento-research/pwa-studio/pull/968#issuecomment-483700462) for more details.

## Proposed Labels for Change Type/Package

FEATURE, BUG

`venia-concept`

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] I have linked an issue to this PR.
- [x] I have indicated the change type and relevant package(s).
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] All CI checks are green (linting, build/deploy, etc).
- [ ] At least one core contributor has approved this PR.

## TODOs

- [x] Sign out doesn't properly clear the cart
- [x] Unit Tests
- [x] Figure out why items are being added with `price: 0` when authenticated

### CODE REVIEW

**Comment by supernova-at** [comment]
Adding the `hold` label until all the TODOs are complete. This PR is not ready to be merged yet.

**Comment by sirugh** [comment]
I had to resolve some conflicts in this just to get it up to date but I'm getting some weird behavior when testing out this workflow. For example if a user is signed in and adds some items, then signs out, there is an error because the guest cart does not exist (the `cartId` belongs to the authenticated user).

When you get a chance I think it'd be worth talking through some of the user flows for this stuff.

**Comment by jimbo** [comment]
Nice work! This looks like a really straightforward replacement of `guestCart` with `cart`, with just a bit of glue to switch endpoints as necessary.

I got this error while creating an account after purchase, maybe unrelated:

```
Error: PUT /rest/V1/guest-carts/MtSZd24zQcpFpvY12AYjkhubykwZ8mSv responded 400 Bad Request: 

Message:

  One or more input exceptions have occurred.

Additional info:

{
    "errors": [
        {
            "message": "\"%fieldName\" is required. Enter and try again.",
            "parameters": {
                "fieldName": "customerId"
            }
        },
        {
            "message": "\"%fieldName\" is required. Enter and try again.",
            "parameters": {
                "fieldName": "storeId"
            }
        }
    ]
}

Magento PHP stack trace: 

#0 /app/vendor/magento/framework/Webapi/ServiceInputProcessor.php(164): Magento\Framework\Webapi\ServiceInputProcessor->processInputError(Array)
#1 /app/vendor/magento/module-webapi/Controller/Rest/InputParamsResolver.php(101): Magento\Framework\Webapi\ServiceInputProcessor->process('Magento\\Quote\\A...', 'assignCustomer', Array)
#2 /app/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Webapi\Controller\Rest\InputParamsResolver->resolve()
#3 /app/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Webapi\Controller\Rest\InputParamsResolver\Interceptor->___callParent('resolve', Array)
#4 /app/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Webapi\Controller\Rest\InputParamsResolver\Interceptor->Magento\Framework\Interception\{closure}()
#5 /app/generated/code/Magento/Webapi/Controller/Rest/InputParamsResolver/Interceptor.php(26): Magento\Webapi\Controller\Rest\InputParamsResolver\Interceptor->___callPlugins('resolve', Array, Array)
#6 /app/vendor/magento/module-webapi/Controller/Rest/SynchronousRequestProcessor.php(85): Magento\Webapi\Controller\Rest\InputParamsResolver\Interceptor->resolve()
#7 /app/vendor/magento/module-webapi/Controller/Rest.php(188): Magento\Webapi\Controller\Rest\SynchronousRequestProcessor->process(Object(Magento\Framework\Webapi\Rest\Request\Proxy))
#8 /app/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#9 /app/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Webapi\Controller\Rest\Interceptor->___callParent('dispatch', Array)
#10 /app/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Webapi\Controller\Rest\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#11 /app/generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(26): Magento\Webapi\Controller\Rest\Interceptor->___callPlugins('dispatch', Array, Array)
#12 /app/vendor/magento/framework/App/Http.php(136): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#13 /app/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#14 /app/pub/index.php(40): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#15 {main}
```

**Comment by jimbo** [comment]
I was able to complete checkout once as a guest user and again as an authed user, so the happy path is working! 🎉 

I concur with @sirugh though, let's work through some of the edge flows.

**Comment by supernova-at** [comment]
> I concur with @sirugh though, let's work through some of the edge flows.

Sounds good - thanks for the reviews!

**Comment by supernova-at** [comment]
> I got this error while creating an account after purchase, maybe unrelated:

I can reproduce this error too - added a TODO for it.

**Comment by supernova-at** [comment]
Hey @ericerway / @awilcoxa , what is the expected behavior in the following scenarios?

## User Logs In

1. Guest (not logged in) user adds some items to cart
1. User logs in

Do items added in step 1 appear in the cart? 

## User Logs Out

1. A logged in user adds items to cart
1. The user logs out

Do items added in step 1 appear in the cart?

## User Logs Back In

1. A logged in user adds some items to cart
1. User logs out
1. User logs back in

Do items added in step 1 appear in the cart?

<hr />

Thanks in advance!

**Comment by ericerway** [comment]
@supernova-at responses below; recommend having @soumya-ashok verify from a UX perspective as well but these are common experiences. Thanks!

**Scenario A: User Logs In**
Do items added in step 1 appear in the cart? Yes.

**Scenario B: User Logs Out**
Do items added in step 1 appear in the cart? No.

**Scenario C: User Logs Back In**
Do items added in step 1 appear in the cart? Yes.

**Comment by supernova-at** [comment]
Updates:

## Use the Existing assignGuestCartToCustomer Function

The existing code was attempting to `PUT guest-carts/{cartId}`, where the actual endpoint is `PUT carts/{cartId}` ([here are the docs](https://devdocs.magento.com/redoc/2.3/customer-rest-api.html#operation/quoteCartManagementV1AssignCustomerPut)).

Further, it turns out we did have an `id` and `store_id`, they were just properties of `user.currentUser`.

Unfortunately, when I send _that_ request, a `401 Unauthorized` is returned:

```json
{
  "message":"The consumer isn't authorized to access %resources.",
  "parameters":{"resources":"Magento_Cart::manage"}
}
```

The assign customer endpoint is part of the "Customer" REST API, which are available only when "using a customer security token", which is hooked up for us via [the M2APIRequest class](https://github.com/magento-research/pwa-studio/blob/develop/packages/peregrine/src/RestApi/Magento2/M2ApiRequest.js#L68).

I have confirmed the request headers do include this token so I am unsure what the server is expecting here or how I can get authorized to access `Magento_Cart::manage`.

**Comment by supernova-at** [comment]
There is a [helpful answer on the Mage2.PRO forums](https://mage2.pro/t/topic/1570/5) that explains how to create Users and set their Roles / Permissions.

I created a "Customer" role and made sure it had the "Manage Carts" permission that my server is complaining about:

Screen Shot 2019-04-15 at 3 16 22 PM

I then created a user, assigned it to my "Customer" role, and signed in to the storefront using this user.

Unfortunately, I am still receiving the error:

```json
{
  "message":"The consumer isn't authorized to access %resources.",
  "parameters":{"resources":"Magento_Cart::manage"}
}
```

**Comment by supernova-at** [comment]
Okay, I verified that the `PUT carts/{cartId}` endpoint only works with an admin token (which requires admin credentials). Because that will take some design and consideration (and possibly waiting for GraphQL will solve it for us), after talking with the team I have broken this work out in to #1144 .

I will update the acceptance criteria for this PR to only include the following:
1. A logged-in customer can complete the checkout flow
1. A guest customer can complete the checkout flow

This PR will **not** address the case where a customer switches between the two.

**Pull request merged**
