### PR TITLE
Adding same input's layout of SignIn into Create Account page

### LINKED ISSUE #912: [BUG] Create Account form input style is different from Sign In
Create Account and Sign In components have different Input styles. 

createAccount.js uses `TextInput`
signIn uses `Input`

image

image

**Please complete the following device information:**
 - Device: [PC]
 - OS: [Ubuntu]
 - Browser [Chrome]

**Please let us know what packages this bug is in regards to:**
- [x] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Possible solutions**
Decide on one or the other.

### PR DESCRIPTION
**Pull request by LucasCalazans**
## Description
I've used the Input component to use the same layout as of "SignIn" page.
It was needed to add some changes to this component to use validations.

## Related Issue
Closes #912.

## Motivation and Context
To use the same layout as the proposed to Venia Theme as we can see at these links:
Login: https://magento.invisionapp.com/share/WQN5F7BYBPG#/screens/318790635
Create Account: https://magento.invisionapp.com/share/WQN5F7BYBPG#/screens/320064949

## How Has This Been Tested?
Local environment.

## Screenshots:
After updates:
https://imgur.com/wTszdgg

## Proposed Labels for Change Type/Package
BUG
venia-concept

## Checklist:
- [x] I have read the **CONTRIBUTING** document.
- [x] I have linked an issue to this PR.
- [x] I have indicated the change type and relevant package(s).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] All CI checks are green (linting, build/deploy, etc).
- [ ] At least one core contributor has approved this PR.

### CODE REVIEW

**Comment by awilcoxa** [comment]
needs review from @soumya-ashok

**Comment by soumya-ashok** [comment]
@LucasCalazans I've had a look at the screenshot of your work. It looks good for the most part, but I had a few comments.

- The styling of the form field needs rounded corners
- The "required" indicator does not seem to be the same size/height on all the fields
- The submit button text needs to be changed to "Create Account"
- The left and right margins on the content are different in the header and top line of text, and different for the form fields
- I noticed that the subscription checkbox is missing. Is this intentional?
- Have all the form field states been addressed? I only see fields in a static state, none that are focused or visited
- Does this work also include validation for the required fields?

**Comment by jimbo** [comment]
This is attempting to use the old `Input` class, so it should probably be reviewed & closed.

**Comment by supernova-at** [comment]
Closing this PR in favor of #1169.

We don't actually want to use the old `Input` component. #1169 removes it to avoid confusion in the future. 

Thanks for your effort on this one though, sorry the direction wasn't as clear as it could have been!

**Pull request closed without merging**
