### PR TITLE
feat(dev): app shell detects env from proxy header

### PR DESCRIPTION
**Pull request by zetlen**
## This PR is a:

[ ] New feature
[ ] Enhancement/Optimization
[x] Refactor
[ ] Bugfix
[ ] Test for existing code
[ ] Documentation

## Summary

When this pull request is merged, it will enable the application shell to emit different script tags when in development vs production mode. When production mode is detected, it emits a script tag for the vendor module. When development mode is detected, it omits this tag. Production mode can work without 

## Additional information

This is a temporary hack; it shouldn't be necessary once app shells are generated on build. For now, it requires disabling of `page_cache` in admin; otherwise, you must `bin/magento cache:flush` every time you switch between dev and prod mode.

### CODE REVIEW

**Comment by mhhansen** [comment]
**relates #30** 

I think will be useful to update this PR with the PHP view file call,
so it doesn't fire up another issue regarding `hardcoded references`
give a shout if want a hand updating this PR.

```
<?php echo $this->getViewFileUrl('js/vendor.js'); ?>
```

**Comment by zetlen** [comment]
@mhhansen Sorry I've become so behind on PRs while I was working on the UPWARD spec. Have you tried `$this->getViewFileUrl('js/vendor.js')` and made it work in `root.phtml`? Since there is no actual block instance in the root file, we didn't have access to that method when we tried.

**Comment by mhhansen** [comment]
No worries! :)
Yes, I tried indeed.. while I was doing some research for [issue #30](https://github.com/magento-research/pwa-studio/issues/30)
Worked for both `client.js` and `vendor.js` files, which are bundled/created at the same level.

That's also why I've created [PR#246](https://github.com/magento-research/pwa-studio/pull/246) for the [issue #30](https://github.com/magento-research/pwa-studio/issues/30) (left a bunch of research in there too, in case it helps others).

This PR will hit the `root.phtml` too, so either #246 needs to be merged/closed first and then this one on top.. or maybe it's better to just leave this one alive, update it with the `getViewFileUrl()` (to avoid introducing hardcoded references) and close/cancel #246.

LMK if you want me to do anything else (tests/changes and even try to rebase latest `master` branch on top and run this tests again) related to this or any other PR/issue related.

### This PR + `getViewFileUrl()`
This is the result having `venia` built for production:
(I know im serving without SSL/TSL, my valetplus went crazy last night I've disabled it)

01 getviewfileurl-renders-ok
02 vendor-client-200-ok


## getViewFileUrl() method available
I think this method is available because `root.phtml` file ends up being an instance of `Magento\Framework\View\Result\Page` which has that method available.

## sidenote
there's a deep research with workbox precache file that I did few weeks ago within the #30
([view comment](https://github.com/magento-research/pwa-studio/issues/30#issuecomment-414388792)) point 2.

**Comment by zetlen** [comment]
@mhhansen Thank you for your detailed research! I'm closing this in favor of #246.

**Pull request closed without merging**
