### PR TITLE
bug: Unwanted content displayed in search suggestion box when there are no results for search

### LINKED ISSUE #1223: [bug]: Unwanted content displayed in search suggestion box when there are no results for search
Steps - 
1. Go to Venia store front and click on search icon.
2. Enter search string which should not return any results. example - afgdsgedf

Expected -  Search suggestion box should just display "No results were found."
Actual - Its displaying some extra content  with above message.

### PR DESCRIPTION
**Pull request by khoa-le**
## Description
Disable render suggestion component when search query have not results.

## Related Issue

Closes #1223.

## Verification Steps

1. Go to Venia store front and click on search icon.
2. Enter search string which should not return any results. example - afgdsgedf
3. Search suggestion box display "No results were found."

## How Have YOU Tested this?
Verification steps above!

## Screenshots / Screen Captures (if appropriate):
Screenshot from 2019-05-17 15-48-56

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento-research/pwa-studio?pullRequest=1252) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento-research/pwa-studio?pullRequest=1252) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: jimbo<br/>:x: khoa-le

**Comment by khoa-le** [comment]
I see this pull request have error when run tests but I don't see any output that help me fix it. Can anyone help?

**Comment by jimbo** [comment]
Wow, Github's cache really didn't show me any conversation on this one.

> Looking at that conditional though, I'm left wondering if autocomplete.js shouldn't house this logic instead.

No, I wouldn't make that change. I think the logic is fine where it is.

**Comment by sirugh** [comment]
Assigned this to @tjwiebell to handle writing/fixing tests.

**Comment by dpatil-magento** [comment]
QA Pass.

**Comment by khoa-le** [comment]
Thank you guys helping me out.

**Pull request merged**
