### PR TITLE
update git clone command to start using https protocol #168

### PR DESCRIPTION
**Pull request by mhhansen**
## This PR is a:

[ ] New feature
[x ] Enhancement/Optimization
[ ] Refactor
[ ] Bugfix
[ ] Test for existing code
[x ] Documentation

## Summary

When this pull request is merged, it will update `pwa-devdocs` docs changing how to clone the repo to this way, using HTTPS protocol:

```
git clone https://github.com/magento-research/pwa-studio.git
```

### CODE REVIEW

**Comment by mhhansen** [comment]
sorry about that -- ttly missed the vagrant section
I'll do some tests for that to ensure the `2.3-develop` branch is downloaded as per this update.

**side note**
I think line 51 should remain as it is now, because it's referencing the `etc/config.yaml.dist` from the  `magento2-vagrant-for-developers` repository. (which prob won't change since their instructions are using SSH protocol).
https://github.com/paliarush/magento2-vagrant-for-developers/blob/2.0/etc/config.yaml.dist#L18

**Comment by mhhansen** [comment]
reached out for help on how to specify a branch while using HTTP Protocol in the `config.yaml` in this line: https://github.com/paliarush/magento2-vagrant-for-developers/blob/2.0/etc/config.yaml.dist#L18

**GIT Protocol with branch:**
```
ce: "git@github.com:magento/magento2.git::2.3-develop"
```

**HTTP Protocol with branch (??)**
```
ce: "https://github.com/magento-research/pwa-studio.git::??????"
```

waiting for feedback to finish this PR

**Comment by mhhansen** [comment]
that's a great hint james 👍
I'll setup up that VM locally tonight to give that a try, so we can push this PR forward
thanks for the insight !

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento-research/pwa-studio?pullRequest=170) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento-research/pwa-studio?pullRequest=170) before we can accept your contribution.<br/>

**Comment by mhhansen** [comment]
worked, and also with the sample data repo!
lmk if looks good

```
[2018-08-07 00:22:03] Checking out CE repository [./init_project.sh]
[2018-08-07 00:27:29] Checking out branch 2.3-develop of CE repository [./init_project.sh]
[2018-08-07 00:27:35] Checking out CE sample data repository [./init_project.sh]
[2018-08-07 00:28:23] Checking out branch 2.3-develop of CE sample data repository [./init_project.sh]
```
magento-and-sampledata

**Comment by jcalcaben** [comment]
Thanks for the contribution @mhhansen !

**Pull request merged**
