### PR TITLE
Resolved Tables overflow in Mobile view

### PR DESCRIPTION
**Pull request by hitesh-wagento**
## Purpose of this PR
Resolved Tables overflow in Mobile view

See https://magento-research.github.io/pwa-studio/technologies/tools-libraries/  Tables overflow in Mobile view

## Affected URLs
https://magento-research.github.io/pwa-studio/technologies/tools-libraries/

## Actual Result
actual

## Expected Result
expected

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento-research/pwa-studio?pullRequest=1263) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento-research/pwa-studio?pullRequest=1263) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: jimbo<br/>:x: hitesh-wagento

**Comment by hitesh-wagento** [comment]
Hi @magento-cicd2 

Can you please review this PR?

Thanks

**Comment by hitesh-wagento** [comment]
Hi @belbiy

Can you please review this PR is correct?

This PR related to : https://github.com/magento-devdocs/devdocs-theme/pull/39

Thanks

**Comment by belbiy** [comment]
@hitesh-wagento , i actually don't like the readability of the new table that you describe in "Expected behavior". It's better to avoid word break like that. 

What if we do something like this instead?

table-scroll-x

This requires some clever CSS to make table to `overflow-x: auto` on small screens. I dont want to add extra wrapper around the table just for this purpose.
Setting `display: block; overflow-x: auto;` to the table works, but it's a trick, we need to investigate a little more.

Also, it would be good to break `Sysadmin/Devops/Backend` by adding spaces like that: `Sysadmin / Devops / Backend`. This will improve the word break.

**Comment by jcalcaben** [comment]
Closing this PR as stale.

**Pull request closed without merging**
