### PR TITLE
893 - Fixing "yarn storybook:venia" command

### LINKED ISSUE #893: [BUG] yarn:storybook throws an "Cannot read property 'js' of undefined"
**Describe the bug**
`yarn storybook:venia` is currently throwing an `UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'js' of undefined` in `/pwa-studio/packages/venia-concept/webpack.config.js:160:55)`.

**To Reproduce**
Steps to reproduce the behaviour:

1. Checkout the latest of `release/2.0` branch. As of this writing it is [this commit](https://github.com/magento-research/pwa-studio/commit/1b85eb9f04d83fcddc24324bc15e0adb68a18fd0)
2. `yarn clean:all`
3. `yarn install`
4. `yarn build`
5. `yarn storybook:venia`

Observe console error:

` 95% emitting WebpackAssetsManifest/Applications/MAMP/htdocs/github/pwa-studio/packages/venia-concept/webpack.config.js:160 load: assets.entrypoints.client.js,`

**Expected behavior**
Expected Storybook to launch, correctly showing Venia components.

**Screenshots**
https://imgur.com/a/zb9WnRN

**Please complete the following device information:**
 - Device: MacBook Pro
 - OS: OSX High Sierra
 - Browser Chrome
 - Version 71.0.3578.98
 - Magento Version 2.3.0
 - NPM version `npm -v` 6.4.1
 - Node Version `node -v` 10.15.1

**Please let us know what packages this bug is in regards to:**
- [x ] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Possible solutions**
Switching `WebpackAssetsManifest` `assets.entrypoints.client.js` to `assets.entrypoints.main.js` in `venia-concept` `webpack.config.js` solves the issue by pointing `load` at the right entry point location.

### PR DESCRIPTION
**Pull request by LucasCalazans**
## Description
Fixing the `WebpackAssetsManifest` plugin. It was getting a wrong object key, causing an error when `yarn storybook:venia` is executed.

## Related Issue
Closes #893.

## Motivation and Context
It was breaking the storybook execution

## How Has This Been Tested?
As the issue says:

1. Checkout the latest of `release/2.0` branch.
2. `yarn clean:all`
3. `yarn install`
4. `yarn build`
5. `yarn storybook:venia`

## Screenshots:
https://imgur.com/a/ZJ6GcKz
https://imgur.com/Do6w7jk

## Proposed Labels for Change Type/Package
BUG
venia-concept

## Checklist:
- [x] I have read the **CONTRIBUTING** document.
- [x] I have linked an issue to this PR.
- [x] I have indicated the change type and relevant package(s).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] All CI checks are green (linting, build/deploy, etc).
- [ ] At least one core contributor has approved this PR.

### CODE REVIEW

**Comment by zetlen** [comment]
Hey, thank you @LucasCalazans ! This is similar to #894 and I commented there that it seems to break the Venia build. I recommend a different approach.

**Comment by LucasCalazans** [comment]
Hey, @zetlen thanks for your review and excellent point.

I've just added a different approach to this bug. Can you check, please?

**Comment by zetlen** [comment]
@LucasCalazans That's a clever trick! I can't merge it because of two things:

1. PWA Studio best practice is to have one single entry point, but that may not always be true; your fix would cause the app shell to load all entry points simultaneously. That would cause Webpack runtime errors.
2. We would rather remove the Venia plugins from the Storybook build than adjust them to work for Storybook.

We're very near our major release right now and I would love to include your contribution. If you can change this PR to implement [this suggestion](https://github.com/magento-research/pwa-studio/pull/894#pullrequestreview-203755474) in the next couple of hours, we can merge it!

If not, then I can make the change and set you as author 💇

**Comment by LucasCalazans** [comment]
@zetlen okay, I see.

Please if you could do that it will be great.

**Comment by zetlen** [comment]
Thanks, but sorry, #894 beat you to it.

**Pull request closed without merging**
