### PR TITLE
Fixed HTML special characters issue

### PR DESCRIPTION
**Pull request by yogeshsuhagiya**
## Description
Fixed HTML special characters issue for the product name on the category page and product view page.

## Related Issue
#984 

## Screenshots (if appropriate):
screenshot

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have linked an issue to this PR.
- [ ] I have indicated the change type and relevant package(s).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] All CI checks are green (linting, build/deploy, etc).
- [ ] At least one core contributor has approved this PR.

### CODE REVIEW

**Comment by supernova-at** [comment]
There were some duplicate commits on this PR too.

Kindly let me know if I've missed anything 👍 .

**Comment by yogeshsuhagiya** [comment]
Hi @sirugh, can you please review this PR now? All checks have passed.

**Comment by sirugh** [comment]
@yogeshsuhagiya something seems off with the commits. Can you remove any commits not made by you for this change? @supernova-at may be able to help.

**Comment by yogeshsuhagiya** [comment]
Hi @supernova-at, how I can remove commits of other peoples?

**Comment by yogeshsuhagiya** [comment]
@supernova-at, @sirugh  Guys, please let me know what I've to do next to move this PR ahead?

**Comment by sirugh** [comment]
@yogeshsuhagiya if the changeset you made here is small enough I would suggest closing this PR and reopening a new branch made off the latest `release/2.0` branch. Then you can cherry-pick or just reproduce your changes and push them up. That's probably the easiest route here.

**Comment by sirugh** [comment]
Replaced with #1010

**Pull request closed without merging**
