### PR TITLE
fix: Webpack fails on missing modules

### LINKED ISSUE #1385: [bug]: loadingIndicator import in cartOptions.js is invalid
**Describe the bug**
We updated the loading indicator to export a `fullPageLoadingIndicator`. We missed one spot in merging in `cartOptions`.

```
WARNING in ./src/components/MiniCart/cartOptions.js 75:14-30
"export 'loadingIndicator' was not found in 'src/components/LoadingIndicator'
 @ ./src/components/MiniCart/editItem.js
 @ ./src/components/MiniCart/body.js
 @ ./src/components/MiniCart/miniCart.js
 @ ./src/components/MiniCart/container.js
 @ ./src/components/MiniCart/index.js
 @ ./src/components/App/app.js
 @ ./src/components/App/container.js
 @ ./src/components/App/index.js
 @ ./src/index.js
```

**To Reproduce**
Check out develop and `yarn install` and `yarn build`. You'll see the warning.
**Expected behavior**

**Possible solutions**
Update the imports to the proper name and double check whether a full page indicator is actually valid in cartOptions now.

**Please complete the following device information:**
 - Device [e.g. iPhone6, PC, Mac, Pixel3]:
 - OS [e.g. iOS8.1, Windows 10]:
 - Browser [e.g. Chrome, Safari]:
 - Browser Version [e.g. 22]:
 - Magento Version:
 - PWA Studio Version:
 - NPM version `npm -v`:
 - Node Version `node -v`:

**Please let us know what packages this bug is in regards to:**
- [x] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

### PR DESCRIPTION
**Pull request by zetlen**
## Description
This PR will soon have the fix for #1385. In the meantime, it has a correction to the build configuration so that we will catch errors like #1385 in the CICD process.

## Related Issue
Closes #1385 
(Or, it will when the actual fix happens)

This uses a Webpack option, `module.strictExportPresence`, that will eventually be deprecated according to Webpack maintainers. At that time, we'll replace it with whatever improved ES6 module dependency management they have.

## Verification Steps

1. Observe that this build is failing.

## Proposed Labels for Change Type/Package

- [ ] major (e.g x.0.0 - a breaking change)
- [ ] minor (e.g 0.x.0 - a backwards compatible addition)
- [x] patch (e.g 0.0.x - a bug fix)

## Checklist:

- [ ] I have updated the documentation accordingly, if necessary.
- [ ] I have added tests to cover my changes, if necessary.

### CODE REVIEW

**Comment by zetlen** [comment]
Observe the glorious field of red indicators @sirugh @dpatil-magento 

Now, Webpack missing modules will actually fail the biild.

**Comment by sirugh** [comment]
Do we want to fix the build in this PR? If we merge without it we will start breaking other PRs as they rebase onto develop. There was a PR opened overnight with the fix, #1391 but it is awaiting some changes from the contributor.

**Comment by sirugh** [comment]
I just merged #1391 and have now rebased this branch onto develop. If/when it passes the build/test checks I will go ahead and merge this PR as well to close the loop.

**Comment by sirugh** [comment]
Looks like there is a failure in `storybook`. I'll fix and push to this PR.

**Comment by sirugh** [comment]
Only outstanding check is danger, which is naturally complaining because we don't actually have an issue for this (it is tied to the one that was resolved by #1391 .

**Pull request merged**
