### PR TITLE
Upgrades Storybook to major version 4

### PR DESCRIPTION
**Pull request by supernova-at**
## This PR is a:

[ ] New feature
[ ] Enhancement/Optimization
[ ] Refactor
[x] Bugfix
[ ] Test for existing code
[ ] Documentation

## Summary

When this pull request is merged, it will fix the current error that is causing Storybook to be unable to load any component stories:

screen shot 2018-11-15 at 1 58 27 pm

## Additional information

The reason Storybook errors out like this is that the `storybook-readme` addon that we are attempting to use ~~wasn't listed as a dependency in `package.json` and therefore was not installed.~~ couldn't be found.

I bumped Storybook (`@storybook/react`) and `storybook-readme` to major version `4` in `pwa-studio` and updated Storybook in `packages/peregrine` and `packages/venia-concept` to match.

Storybook now finds the `storybook-readme` addon at the higher level and therefore it does not need to be listed as a dev dependency in `peregrine`.

After this change, Storybook works as intended:

screen shot 2018-11-15 at 2 06 59 pm

## Potential Risk

Upgrading Storybook outside of the `peregrine` project may introduce some breakages.

I couldn't find anywhere else in `pwa-studio` or `packages/venia-concept` where Storybook was actually being used though, so I think the risk is none.

But with that being the case, should we remove the Storybook dependency from `packages/venia-conept`?

## Note!

This PR is opened against the `release/2.0` branch. If this is incorrect, kindly let me know and I'll point it to a different branch 🥂 .

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento-research/pwa-studio?pullRequest=508) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento-research/pwa-studio?pullRequest=508) before we can accept your contribution.<br/><hr/>**Andrew Terranova** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by zetlen** [comment]
Super weird. It may be that the versions are incompatible--can you try upgrading `storybook-readme`?

**Comment by supernova-at** [comment]
> It may be that the versions are incompatible

That was it!

I upgraded `@storybook/react` and `storybook-readme` to major version `4` and it works without having to install `storybook-readme` in `peregrine`.

I also bumped `@storybook/react` in `peregrine` to version 4 to match.

**Comment by supernova-at** [comment]
For completeness

> can you try upgrading storybook-readme?

I did try this and it did not work without also bumping `@storybook/react`.

**Pull request merged**
