### PR TITLE
1329 continue shopping empty cart button

### LINKED ISSUE #1329: "Continue Shopping" button style in empty shopping cart
Currently, the button looks like this -

The correct styling would be -

with the button changing to the dark teal in the focused state without the dark gray border seen in the first screenshot.

### PR DESCRIPTION
**Pull request by johnhughes1984**
## Description
Fixes styles for the mini cart empty cart 'Continue Shopping' button and refactors the code to handle closure of the drawer by moving functionality up into the main mini cart component.

The 'Continue Shopping' button element has been refactored to use the same component as the 'Sign In' / 'Create Account' buttons in the left hand drawer for consistency.

## Related Issue
Closes # .

## Verification Steps
1. Go to the homepage.
2. Open the minicart (ensure no products are in your cart)
3. The 'Continue Shopping' button should be visible
4. The styles for the 'Continue Shopping' button should be as described in the issue
5. Clicking the 'Continue Shopping' button should close the mini cart drawer

## How have YOU tested this?
By following the verification steps

## Proposed Labels for Change Type/Package
- [ ] major (e.g x.0.0 - a breaking change)
- [ ] minor (e.g 0.x.0 - a backwards compatible addition)
- [x] patch (e.g 0.0.x - a bug fix)

## Checklist:
- [x] I have updated the documentation accordingly, if necessary.
- [x] I have added tests to cover my changes, if necessary.

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento-research/pwa-studio?pullRequest=1367) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento-research/pwa-studio?pullRequest=1367) before we can accept your contribution.<br/>

**Comment by supernova-at** [comment]
I have added the `hold` label to this PR and #1264. They solve the same problem in different ways so we just need to decide which solution we want to move forward with.

Further, this work needs to be incorporated into the existing #1266 MiniCart refactor, or added as a fast follow.

**Comment by dpatil-magento** [comment]
@supernova-at  Merged #1264 as discussed. Can we close this one or you think we might need it?

**Comment by supernova-at** [comment]
Unfortunately the big giant mini cart refactor landed before this got in. A lot of what is in this PR is already in so I'm going to close this one out. Sorry John!

**Pull request closed without merging**
