### PR TITLE
bug: Add / to graphql validation endpoint

### PR DESCRIPTION
**Pull request by sirugh**
## Description
The graphql validation endpoint we added in #1004 did not have a `/`. Since we don't mandate that the `MAGENTO_BACKEND_URL` end with a forward slash we should add one here to be safe.

## Motivation and Context

```js
$ yarn run download-schema && graphql validate-magento-pwa-queries --project venia
$ graphql get-schema --project venia
⚠ request to https://release-dev-231-npzdaky-zddsyhrdimyra.us-4.magentosite.cloudgraphql failed, reason: getaddrinfo ENOTFOUND release-dev-231-npzdaky-zddsyhrdimyra.us-4.magentosite.cloudgraphql release-dev-231-npzdaky-zddsyhrdimyra.us-4.magentosite.cloudgraphql:443
Validating GraphQL queries in venia project...
✖ An error occurred:
Could not find a schema at lastCachedGraphQLSchema.json.
 Run `graphql get-schema --project venia` to download the schema before running validate-magento-pwa-queries.
error Command failed with exit code 1.
```

## Verification
To verify, set the `MAGENT_BACKEND_URL` in your `.env` to something without a `/` like `MAGENTO_BACKEND_URL="https://release-dev-231-npzdaky-zddsyhrdimyra.us-4.magentosite.cloud"`

Then from root run `yarn run validate-queries`. It should fail.
Then check out this PR and run it again, and it should pass.

## How Has This Been Tested?
Above verification. Also tested with url ending with `/`.

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] I have linked an issue to this PR.
- [x] I have indicated the change type and relevant package(s).
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] All CI checks are green (linting, build/deploy, etc).
- [x] At least one core contributor has approved this PR.

### CODE REVIEW

**Comment by zetlen** [comment]
This is a good addition, but it's a reminder to me that we need proper URI construction as part of UPWARD.

**Comment by sirugh** [comment]
Yea I felt like its sort of papering over an issue but `//` is better than nothing :)

**Comment by brendanfalkowski** [comment]
Just tested this out, and `yarn run build` fails for me on the following:

⚠ request to https://m2pwa.test//graphql failed, reason: unable to verify the first certificate

Opening `https://m2pwa.test//graphql` and `https://m2pwa.test//graphql` in the browser, both lead to this:

Screen Shot 2019-03-21 at 3 09 48 PM

I tried changing `.env` to contain or omit the trailing slash, but no effect.

I'm working off "pwastudio :: develop" branch. Any ideas?

**Comment by sirugh** [comment]
@brendanfalkowski I've not seen the certificate error before. I think that is unrelated to this fix. Open an issue please!

**Pull request merged**
