### PR TITLE
Add Shell Script to install Venia sample data modules via composer

### PR DESCRIPTION
**Pull request by davidverholen**
## This PR is a:

[ ] New feature
[x] Enhancement/Optimization
[ ] Refactor
[ ] Bugfix
[ ] Test for existing code
[ ] Documentation

## Summary

When this pull request is merged, it will add a shell script to deploy the venia sample data modules

## Additional information
See https://github.com/magento-research/pwa-studio/issues/290
and https://github.com/magento-research/pwa-studio/issues/261

### CODE REVIEW

**Comment by mhhansen** [comment]
good stuff !
was trying this PR within a local M2.3, and failed against `PTMET-public/module-customer-sample-data-venia`:
```
[Composer\Repository\InvalidRepositoryException]
  No valid composer.json was found in any branch or tag of git@github.com:PMET-public/module-customer-sample-data-venia.git, could not load a package from it.
```
https://github.com/PMET-public/module-customer-sample-data-venia/blob/master/composer.json

Did you get the whole pack of modules installed OK? maybe I'm missing something:
I've placed it at the folder root of M2.3 instance, gave it `+x` permissions, and ran it.

**Comment by mhhansen** [comment]
nevermind, I think that error was related to my `.composer/cache` or something.
I've added `-vvv` to the `composer` command within the script to see what was failing, but within this second run it ended up OK.

**Comment by davidverholen** [comment]
@mhhansen thanks for the feedback! Did you try to execute it without copying it first? Did not try it myself and not that sure about shell scripts and directory context tbh. 

Maybe there is also a way to detect the composer root of the project in the script. Not sure about this yet.

**Comment by davidverholen** [comment]
@zetlen in https://github.com/magento-research/pwa-studio/issues/261 you wrote that it should also execute setup:upgrade. Should I add this step to the script?

Basically I took the current bin/magento sampledata:deploy command as an example which only adds the composer dependencies but does not install them yet

**Comment by zetlen** [comment]
Awesome, thank you @davidverholen ! I'm trying it out now on a cloud instance I'm trying to deploy.

**Comment by mhhansen** [comment]
hey @davidverholen, I didn't try it without copying into the mage root folder (I think it won't work otherwise).

I made a small improvement to your version (for my self enjoyment heh), that it asks for the magento root folder + confirms the action like `are you sure you wanna continue` :)
https://gist.github.com/mhhansen/19775bcf93614f5f9db34b90273fa2b8


screen shot 2018-10-08 at 8 52 17 am

**Comment by mhhansen** [comment]
gist updated file!

@davidverholen feel free to grab that and update/test it with your PR

**Comment by zetlen** [comment]
@mhhansen I like interactive commands, but there should be a `--yes` flag for this to run as part of an automated process...

**Comment by davidverholen** [comment]
thanks guys! I'll have no time tomorrow, but I made myself a reminder for Wednesday to apply the changes

**Comment by mhhansen** [comment]
ttly, it needs to be `--yes` or can be something like `--skip-interactive`, or `--force` ?
I think it will also need another param to also specify the magento absolute path?

ending it's running like:
```
bash deployVeniaSampleData.sh --yes --path=/var/www/magento
```

**Comment by mhhansen** [comment]
@zetlen gist updated
https://gist.github.com/mhhansen/19775bcf93614f5f9db34b90273fa2b8
```
bash deployVeniaSampleData.sh --yes --path="/your/absolute/path/magento/230"
```

**Comment by zetlen** [comment]
@davidverholen Confirmed that @mhhansen's additions work well. If you're busy, I can amend your commit and put it under joint authorship for you two, and then merge it!

**Comment by mhhansen** [comment]
**FYI** if someone face an error like next shot:
composer-rate-limit-error

it could be related to [composer api rate limits](https://github.com/composer/composer/blob/master/doc/articles/troubleshooting.md#api-rate-limit-and-oauth-tokens)

you can resolve this issue by creating a `auth.json` in your M2 root folder, with a [personal token](https://blog.github.com/2013-05-16-personal-api-tokens/), like so

```
# `auth.json` file in your M2 project root folder
{
    "github-oauth": {
        "github.com": "xxxxxxxxxxxxxxxxxx"
    }
}
```

after that, go an run the script again, and things should run smoothly now:
script-running

**Comment by speedy008** [comment]
Hi all,
I am facing the issue while installing venia-sample-data, Please find below screenshot
unstable-venia

can anyone guide me to solve this error.

Thanks

**Comment by tjwiebell** [comment]
@speedy008 - can try using `minimum-stability: 'dev'` in your `composer.json`? I thought this script used inline overrides with `dev-master@dev` constraints, but that may not be working as expected. If you're still having issues, could you please open a new issue using the Bug ticket, and we can investigate.

**Comment by NeoSolax** [comment]
Generate a personal token by the following the instruction here. https://github.blog/2013-05-16-personal-api-tokens/

Replace the token with xxxxxxxxx and run.
/usr/local/bin/composer config -g github-oauth.github.com xxxxxxxxx

Now you can navigate to the document root and run 
bash ./deployVeniaSampleData.sh --yes

**Pull request merged**
