### PR TITLE
root.phtml remove hardcoded reference client.js #30

### LINKED ISSUE #30: root.phtml includes hardcoded reference to pub/static
_From @fooman on May 9, 2018 0:22_

Magento can be run with either 
1. the pub/ folder as the document root (most should use this one)
2. or from the Magento root folder.

Using the hardcoded `<script src="/pub/static/frontend/Magento/venia/en_US/client.js"></script>` in root.phtml assumes 2.

`<script src="<?= $this->getViewFileUrl('client.js')?>"></script>` will likely work better. It resolves to either option and also respects the versioning setting.

_Copied from original issue: magento-research/venia-pwa-concept#63_

### PR DESCRIPTION
**Pull request by mhhansen**
## This PR is a:

[ ] New feature
[x] Enhancement/Optimization
[ ] Refactor
[x] Bugfix
[ ] Test for existing code
[ ] Documentation

## Summary

Fixes #30 
When this pull request is merged, it will remove hardcoded reference to the `client.js` in the `root.html` and call the file by using `getViewFileUrl()` which is a core method for calling storefront files.

## Additional information
There's more on this within #30 comments, plus some other observations regarding service worker and precache file.

https://github.com/magento-research/pwa-studio/issues/30#issuecomment-412380878
https://github.com/magento-research/pwa-studio/issues/30#issuecomment-414388792

**Shots regarding this change**
dom-tab

network-tab-clientjs

### CODE REVIEW

**Comment by mhhansen** [comment]
I'm not seeing the _Reviewers_ menu in the sidebar.
Anyone with access, please do me that favor 😄 

https://help.github.com/articles/requesting-a-pull-request-review/

**Comment by mhhansen** [comment]
I'd prefer to leave it working and other related tasks/issues, cause it will rise fewer questions and doubts for new developers that jumps in later. I'll stick till this friday/sunday with it. If I can pull it off, then we leave 0.x fully working so others can play around. sounds good?

**Comment by zetlen** [comment]
Hey @mhhansen, I'm closing this as a bookkeeping task, because if I'm understanding you correctly, it's on hold until you can confirm that it works in both the devserver and on production in the 1.x (theme) branch. Please reopen it any time you see fit!

**Comment by mhhansen** [comment]
sure, no worries! -- yesterday realized how things are going under the hood, and also notice that some packages were outdated in my local (avoiding me to see the `development mode` problem with this PR).
I think I've also isolated the exact commit right before `1.x` architecture started to being pushed.
As soon I confirm that, we could create a branch from starting from that and merge this one on top.

**Pull request closed without merging**
