### PR TITLE
strip prop types for production builds

### PR DESCRIPTION
**Pull request by mtbottens**
@DrewML 
Moved https://github.com/magento-research/venia-pwa-concept/pull/93

Not sure whats going on with package-lock changes.
Using:
nvm 0.33.11
node 8.11.3
npm 5.6.0

I can remove each package-lock.json from this commit if needed.

### CODE REVIEW

**Comment by DrewML** [comment]
Thanks @mtbottens! I'll review this and look into the package lock stuff today.

**Comment by DrewML** [comment]
The changes in `packages/venia-concept/package-lock.json` are expected, but the others changing are...odd.

Did those change when you ran `npm install` in the root of the project, or did they change when you installed the babel plugin?

**Comment by mtbottens** [comment]
It's happening for me on npm install in project root.

Can consistently change package-lock.json by doing the following:
```bash
rm -rf node_modules packages/peregrine/node_modules packages/pwa-buildpack/node_modules packages/venia-concept/node_modules
npm install
git status
```

Yesterday it was happening on lerna bootstrap.

**Comment by DrewML** [comment]
That's bizarre. Can you see what happens if you purge all `node_modules` dirs and then do:

- `npm i -g npm@6`
- `npm install`

**Comment by mtbottens** [comment]
Thanks man!

**Comment by DrewML** [comment]
Thank _you_!

Listing results here for posterity's sake.

| Chunk        | Before           | After  |
| ------------- |:-------------:| -----:|
| Product      | 218kb | 215kb |
| Category      | 180kb      |   178kb |

**Pull request merged**
